# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

orbs: 
  slack: circleci/slack@4.12.5
  aws-s3: circleci/aws-s3@3.1.1
executors:
  scratchjr-website-executor:
    docker:
      - image: cimg/node:17.0.0
    resource_class: small

aliases:
  - &deploy
    steps:
      - aws-s3/configure:
          role-arn: AWS_OIDC_IAM_ROLE
      - aws-s3/sync:
          aws-region: AWS_REGION
          from: ./build
          to: '${S3_BUCKET_NAME_develop}'
      - slack/notify:
          channel: C033BNUG2F7
          event: fail
          template: SLACK_SCRATCHJR_FAIL
      - slack/notify:
          channel: C033BNUG2F7
          event: pass
          template: SLACK_SCRATCHJR_SUCCESS
jobs:
  setup_and_deploy:
    executor: scratchjr-website-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Lint Site Code
          command: npm run test
      - run:
          name: Build Site
          command: npm run build
      - when:
          condition:
              or:
                - equal: [ develop, << pipeline.git.branch >> ]
          <<: *deploy
      - when:
          condition:
              or:
                - equal: [ master, << pipeline.git.branch >> ]
          <<: *deploy
workflows:
  build_and_deploy_scratchjr-website:
    jobs: 
      - setup_and_deploy:
          name: Setup and Deploy ScratchJR Website
          context:
            - slack-notifications
